database:
  enabled: true
  type: "mariadb"
  host: "127.0.0.1"
  port: 3306
  name: "luna"
  username: "root"
  password: ""
  options:
    useSSL: false
    serverTimezone: "UTC"

http:
  enabled: true
  host: "0.0.0.0"
  port: 32452
  pathPrefix: "/api"

heartbeat:
  timeoutSeconds: 20

logging:
  ansi: true
  defaultScope: "LunaCoreVelocity"
  level: "INFO"
  pluginMessaging:
    enabled: false
