logging:
  ansi: true
  level: "INFO"
  pluginMessaging:
    enabled: false
  heartbeatTransport:
    enabled: false

heartbeat:
  enabled: true
  endpoint: "http://127.0.0.1:32452/api/heartbeat"
  serverName: ""
  intervalSeconds: 5
  connectTimeoutMillis: 3000
  readTimeoutMillis: 3000

messaging:
  rabbitmq:
    enabled: false
    uri: "amqp://guest:guest@127.0.0.1:5672/%2F"
    exchange: "luna.plugin-messaging"
    proxyQueue: "luna.proxy.messaging"
    backendQueuePrefix: "luna.backend."
    localServerName: ""
    connectionTimeoutMillis: 5000
    requestedHeartbeatSeconds: 15
