database:
  enabled: true
  type: "sqlite"
  host: "127.0.0.1"
  port: 3306
  name: "luna.db"
  username: "root"
  password: ""
  options:
    useSSL: false
    serverTimezone: "UTC"

http:
  enabled: false
  host: "0.0.0.0"
  port: 8080
  pathPrefix: "/api"

help:
  gui:
    title: "<gold>Hướng Dẫn Lệnh"
    size: 54
    pageSize: 45
  search:
    prompt: "🔍 Nhập từ khóa tìm kiếm trên chat"
    cancelKeywords:
      - "huy"
      - "cancel"

strings:
  money:
    currencySymbol: '<#FCF0A0>⛃</#FCF0A0>'
    grouping: true
    format: '<#FFDFD4><b>{amount}</b></#FFDFD4> {symbol}'

logging:
  ansi: true
  defaultScope: "LunaCore"
  level: "INFO"
