name: LunaMigrator
version: ${version}
main: dev.belikhun.luna.migrator.LunaMigratorPlugin
api-version: '1.21'
description: UUID migration helper for Luna auth stack.
authors:
  - Belikhun
commands:
  migrate:
    description: Đánh dấu trạng thái migrate UUID một lần.
    usage: /migrate [tên_cũ]
dependencies:
  server:
    LunaCore:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    HuskHomes:
      load: BEFORE
      required: false
      join-classpath: true
