name: LunaMigrator
version: ${version}
main: dev.belikhun.luna.migrator.LunaMigratorPlugin
api-version: '1.21'
description: UUID migration helper for Luna auth stack.
authors:
  - Belikhun
commands:
  migrate:
    description: Đánh dấu trạng thái migrate UUID một lần.
    usage: /migrate [oldname]
permissions:
  lunamigrator.use:
    description: Cho phép dùng /migrate và /migrate confirm
    default: "true"
  lunamigrator.manual:
    description: Cho phép dùng /migrate manual
    default: "op"
    children:
      lunamigrator.use: true
  lunamigrator.test:
    description: Cho phép dùng /migrate test
    default: op
    children:
      lunamigrator.use: true
  lunamigrator.clear:
    description: Cho phép dùng /migrate clear
    default: op
    children:
      lunamigrator.use: true
dependencies:
  server:
    LunaCore:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    HuskHomes:
      load: BEFORE
      required: false
      join-classpath: true
