modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="lunacoremessaging"
version="${version}"
displayName="LunaCoreMessaging"
description='''
Forge transport bootstrap for Luna backend messaging.
'''

[[dependencies.lunacoremessaging]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.lunacoremessaging]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="SERVER"

[[dependencies.lunacoremessaging]]
modId="lunacore"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.lunacoremessaging]]
modId="luckperms"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="SERVER"
